### ISSUE TITLE
Theme Color Change

### ISSUE THREAD

**Issue by yujiangpu20** [Hanchao-Zhang/Hanchao-Zhang.github.io#1]
Thanks for your excellent repo! I am wondering how to modify the global theme color. I tried to modify assets/css/publication.css and style.scss but but neither work.

**Comment by Hanchao-Zhang** [comment]
you can change the color in the minimal-light.scss file. There is no global option for now.

**Comment by Hanchao-Zhang** [comment]
> Thanks for your excellent repo! I am wondering how to modify the global theme color. I tried to modify assets/css/publication.css and style.scss but but neither work.

You can change the color in the minimal-light.scss file. There is no global option for now.
